package com.myspace.finanmovilsa.implementacion;

import com.myspace.finanmovilsa.model.bo.Credito;
import com.myspace.finanmovilsa.interfaz.ITotalEndeudamiento;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TotalEndeudamiento implements ITotalEndeudamiento {

    @Override
    public Credito calcularEnd(Credito credito){
        Integer a = credito.getSalPersona() - credito.getGasPersona();
        Integer p = (a*25)/100 ;
        Integer endeudamiento = p / credito.getTimAmortizacion();
        
        credito.setTotEndeudamiento(endeudamiento);
        
        //System.out.print("ENDEUDAMIENTO");
        
        return credito;
        
    }




}