package com.myspace.finanmovilsa.interfaz;

import com.myspace.finanmovilsa.model.bo.Credito;

/**
 * This class was automatically generated by the data modeler tool.
 */

public interface ITotalEndeudamiento{

    public Credito calcularEnd(Credito credito);

}