package com.myspace.finanmovilsa.model.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cabe implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Fecha Actual")
	private java.lang.String fechaActual;
	@org.kie.api.definition.type.Label("Fecha Registro")
	private java.lang.String fechaRegistro;
	public Cabe() {
	}

	public java.lang.String getFechaActual() {
		return this.fechaActual;
	}

	public void setFechaActual(java.lang.String fechaActual) {
		this.fechaActual = fechaActual;
	}

	public java.lang.String getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(java.lang.String fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Cabe(java.lang.String fechaActual, java.lang.String fechaRegistro) {
		this.fechaActual = fechaActual;
		this.fechaRegistro = fechaRegistro;
	}

}