package com.myspace.finanmovilsa.model.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Datime {

	public String formatted;

	public String getFormatted() {
		return formatted;
	}

	public Datime() {
	}

	public Datime(java.lang.String formatted) {
		this.formatted = formatted;
	}

}