package com.myspace.finanmovilsa.model.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DatosContacto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Direccion")
	private java.lang.String direccion;
	@org.kie.api.definition.type.Label(value = "Telefono")
	private java.lang.String telefono;
	@org.kie.api.definition.type.Label(value = "Email")
	private java.lang.String emal;

	public DatosContacto() {
	}

	public java.lang.String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(java.lang.String direccion) {
		this.direccion = direccion;
	}

	public java.lang.String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(java.lang.String telefono) {
		this.telefono = telefono;
	}

	public java.lang.String getEmal() {
		return this.emal;
	}

	public void setEmal(java.lang.String emal) {
		this.emal = emal;
	}

	public DatosContacto(java.lang.String direccion, java.lang.String telefono,
			java.lang.String emal) {
		this.direccion = direccion;
		this.telefono = telefono;
		this.emal = emal;
	}

}