package com.myspace.finanmovilsa.model.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Validaciones implements java.io.Serializable {

	@org.kie.api.definition.type.Label(value = "Estado Credito")
	private java.lang.String estado;
	@org.kie.api.definition.type.Label(value = "Razon")
	private java.lang.String razon;
	@org.kie.api.definition.type.Label(value = "Codigo")
	private java.lang.String codigo;

	public Validaciones() {
	}

	public java.lang.String getEstado() {
		return this.estado;
	}

	public void setEstado(java.lang.String estado) {
		this.estado = estado;
	}

	public java.lang.String getRazon() {
		return this.razon;
	}

	public void setRazon(java.lang.String razon) {
		this.razon = razon;
	}

	public java.lang.String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(java.lang.String codigo) {
		this.codigo = codigo;
	}

	public Validaciones(java.lang.String estado, java.lang.String razon,
			java.lang.String codigo) {
		this.estado = estado;
		this.razon = razon;
		this.codigo = codigo;
	}

}